### ISSUE TITLE
Can't create expectation

### ISSUE THREAD

**Issue by Gounlaf** [mcustiel/phiremock-server#1]
Hi @mcustiel,

Using the new client & server packages, I got this error:

```
GuzzleHttp\Exception\ServerException : Server error: `POST http://auth/__phiremock/expectations` resulted in a `500 Internal Server Error` response:
{"result" : "ERROR", "details" : {"request":"Field request, was set with invalid value: NULL"}}
```

The expectation is simple (mine are more complex, but with this one or more complex the bug is still here):

```
            Phiremock::on(
                A::getRequest()
                    ->andUrl(Is::equalTo('/some/uri'))
            )->then(
                Respond::withStatusCode(200)
            )
```

It might be related to the client, but I'm not sure...

Server logs:
```
[2020-10-02T14:27:47.536946+00:00] stdoutLogger.INFO: Starting Phiremock... [] []
[2020-10-02T14:27:47.547541+00:00] stdoutLogger.INFO: Phiremock http server listening on 0.0.0.0:80 [] []
[2020-10-02T14:30:20.883397+00:00] stdoutLogger.WARNING: Invalid request received [] []
```

I can't (yet) go deeper to find what the issue. I've just update package and client setup using the client factory.

Regards,

**Comment by mcustiel** [comment]
Hello @Gounlaf 
Thanks for reporting it. Could you please run phiremock server with the debug flag and send me the logs? Thank you very much.

**Comment by Gounlaf** [comment]
Hi @mcustiel,

I was testing the new client against the old server...
There aare no problem, sorry!
