### ISSUE TITLE
proxyTo with request URI regexp matching

### ISSUE THREAD

**Issue by VoDmAl** [mcustiel/phiremock-server#14]
Thanks for the great solution for simulating requests to remote services.

I tried, but couldn't find how in "proxyTo" mode I can pass the original request URI. In the "response" mode, it is possible to use regexp matching. But it does not work for a proxy.

```
{
  "version": "2",
  "on": {
    "url": { "matches": "~^/v3/(.*)~"}
  },
  "then": {
    "proxyTo": "https://example.com/v3/${url.1}"
  },
  "priority": 0
}
```

So when I send request to http://127.0.0.1/v3/some/thing, I would like to see it to be proxied to https://example.com/v3/some/thing

Perhaps I made some mistake? If this is not possible, can it be added?

Thank you!

**Comment by mcustiel** [comment]
Hello @VoDmAl 
Thanks for pointing it out. Right now it is not possible to do what you are trying, but I think it's possible to implement it. 
I will do it in the next days.

**Comment by VoDmAl** [comment]
Awesome! You did a lot of refactorings, adding this feature. Thank you so much!
