### ISSUE TITLE
Compatibility for php 8.1

### ISSUE THREAD

**Issue by darkmatus** [mcustiel/phiremock-server#6]
It would be nice if phiremock (-server) would be compatible with php8.1. Currently it is blocked.
Composer gives the following output:

> - mcustiel/phiremock v2.1.1 requires mcustiel/phiremock-server ^1.0 -> satisfiable by mcustiel/phiremock-server[v1.0.0, v1.1.0, v1.1.1, v1.1.2].
> - mcustiel/phiremock[v2.0.0, ..., v2.1.0] require php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
> - mcustiel/phiremock-server[v1.0.0, ..., v1.1.1] require php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.

It would also be nice if symfony/console 6 is supported (if possible)

**Comment by edudobay** [comment]
The latest versions don't have that conflict anymore (since `mcustiel/phiremock v2.1.1`), but `symfony/console ^6.0` is not yet supported. Is there any reason not to support it?

**Comment by edudobay** [comment]
https://github.com/mcustiel/phiremock-server/pull/7 and https://github.com/mcustiel/phiremock-server/releases/tag/v1.1.3 seem to have solved this :)
